@api = http://localhost:3000/api

### Register
POST {{api}}/auth/register
Content-Type: application/json

{
    "email" : "novillo.matias1@gmail.com",
    "password" : "1234",
    "username": "Carlos"
}

### Login
POST {{api}}/auth/login
Content-Type: application/json

{
    "email" : "novillo.matias1@gmail.com",
    "password" : "1234"
}