@api = http://localhost:3000/api

### Select all
{{api}}/Shop/Product

### Select 1
{{api}}/Shop/Product/657b59d6a088d5a86a51a00b

### Insert
POST {{api}}/Shop/Product
Content-Type: application/json

{
    "name": "Apple",
    "isAvailable": true,
    "quantity": 5,
    "createdDate": "1995-05-12T00:00:00.001Z",
    "price": 3.14
}

### Update
PATCH {{api}}/Shop/Product/657b59d6a088d5a86a51a00b
Content-Type: application/json

{
    "name": "Motorola",
    "isAvailable": true,
    "quantity": 5,
    "createdDate": "1995-05-12T00:00:00.001Z",
    "price": 3.14
}

### Delete
DELETE {{api}}/Shop/Product/657b59d6a088d5a86a51a00b